/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import java.util.Random;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import laundry_service.Customer;
import laundry_service.Employee;
import laundry_service.LaundryInfo;
import laundry_service.ServicesAvailed;
import laundry_service.Transaction;


/**
 *
 * @author Franklin
 */
public class CustInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustInfo
     */
    public CustInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        csw = new javax.swing.JSpinner();
        bsq = new javax.swing.JSpinner();
        jsq = new javax.swing.JSpinner();
        blsq = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        csq = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        wsq = new javax.swing.JSpinner();
        wsw = new javax.swing.JSpinner();
        bsw = new javax.swing.JSpinner();
        jsw = new javax.swing.JSpinner();
        blsw = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        deliverycheck = new javax.swing.JCheckBox();
        coloredcheck = new javax.swing.JCheckBox();
        whitescheck = new javax.swing.JCheckBox();
        heavycheck = new javax.swing.JCheckBox();
        drycheck = new javax.swing.JCheckBox();
        ironcheck = new javax.swing.JCheckBox();
        rushcheck = new javax.swing.JCheckBox();
        pickupcheck = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        namefield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Transaction");
        setPreferredSize(new java.awt.Dimension(832, 950));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(817, 745));
        jPanel1.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(440, 290, 20, 510);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(20, 290, 760, 2);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(30, 800, 760, 10);

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(817, 745));
        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Services Availed");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(490, 250, 190, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Name");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 120, 90, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Contact Number");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 160, 160, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Address");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 200, 150, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Laundry Information");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 260, 220, 30);
        jPanel2.add(csw);
        csw.setBounds(340, 330, 60, 30);
        jPanel2.add(bsq);
        bsq.setBounds(200, 430, 60, 30);
        jPanel2.add(jsq);
        jsq.setBounds(200, 480, 60, 30);
        jPanel2.add(blsq);
        blsq.setBounds(200, 530, 60, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Weight");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(340, 290, 90, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("Quantity");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(190, 290, 90, 30);
        jPanel2.add(csq);
        csq.setBounds(200, 330, 60, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(440, 250, 20, 490);
        jPanel2.add(wsq);
        wsq.setBounds(200, 380, 60, 30);
        jPanel2.add(wsw);
        wsw.setBounds(340, 380, 60, 30);
        jPanel2.add(bsw);
        bsw.setBounds(340, 430, 60, 30);
        jPanel2.add(jsw);
        jsw.setBounds(340, 480, 60, 30);
        jPanel2.add(blsw);
        blsw.setBounds(340, 530, 60, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Basic Information");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(20, 70, 190, 40);

        deliverycheck.setBackground(new java.awt.Color(51, 51, 0));
        deliverycheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deliverycheck.setForeground(new java.awt.Color(240, 240, 240));
        deliverycheck.setText("Delivery");
        deliverycheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverycheckActionPerformed(evt);
            }
        });
        jPanel2.add(deliverycheck);
        deliverycheck.setBounds(500, 520, 160, 30);

        coloredcheck.setBackground(new java.awt.Color(51, 51, 0));
        coloredcheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coloredcheck.setForeground(new java.awt.Color(240, 240, 240));
        coloredcheck.setText("Colored");
        jPanel2.add(coloredcheck);
        coloredcheck.setBounds(500, 310, 160, 30);

        whitescheck.setBackground(new java.awt.Color(51, 51, 0));
        whitescheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        whitescheck.setForeground(new java.awt.Color(240, 240, 240));
        whitescheck.setText("Whites");
        whitescheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whitescheckActionPerformed(evt);
            }
        });
        jPanel2.add(whitescheck);
        whitescheck.setBounds(500, 340, 160, 30);

        heavycheck.setBackground(new java.awt.Color(51, 51, 0));
        heavycheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heavycheck.setForeground(new java.awt.Color(240, 240, 240));
        heavycheck.setText("Heavy");
        heavycheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavycheckActionPerformed(evt);
            }
        });
        jPanel2.add(heavycheck);
        heavycheck.setBounds(500, 370, 160, 30);

        drycheck.setBackground(new java.awt.Color(51, 51, 0));
        drycheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drycheck.setForeground(new java.awt.Color(240, 240, 240));
        drycheck.setText("Dry Clean");
        drycheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drycheckActionPerformed(evt);
            }
        });
        jPanel2.add(drycheck);
        drycheck.setBounds(500, 400, 160, 30);

        ironcheck.setBackground(new java.awt.Color(51, 51, 0));
        ironcheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ironcheck.setForeground(new java.awt.Color(240, 240, 240));
        ironcheck.setText("Iron");
        ironcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ironcheckActionPerformed(evt);
            }
        });
        jPanel2.add(ironcheck);
        ironcheck.setBounds(500, 430, 160, 30);

        rushcheck.setBackground(new java.awt.Color(51, 51, 0));
        rushcheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rushcheck.setForeground(new java.awt.Color(240, 240, 240));
        rushcheck.setText("Rush");
        rushcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rushcheckActionPerformed(evt);
            }
        });
        jPanel2.add(rushcheck);
        rushcheck.setBounds(500, 460, 160, 30);

        pickupcheck.setBackground(new java.awt.Color(51, 51, 0));
        pickupcheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pickupcheck.setForeground(new java.awt.Color(240, 240, 240));
        pickupcheck.setText("Pick-up");
        pickupcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupcheckActionPerformed(evt);
            }
        });
        jPanel2.add(pickupcheck);
        pickupcheck.setBounds(500, 490, 160, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(20, 250, 760, 2);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("NEW TRANSACTION");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(160, 16, 470, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Colored");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 330, 100, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Whites");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(30, 380, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Bedsheet");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 430, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Jeans");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 480, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Blanket");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 530, 100, 30);

        savebutton.setText("Place order");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(savebutton);
        savebutton.setBounds(660, 70, 120, 50);
        jPanel2.add(namefield);
        namefield.setBounds(190, 130, 320, 20);
        jPanel2.add(contactfield);
        contactfield.setBounds(190, 170, 320, 20);
        jPanel2.add(addressfield);
        addressfield.setBounds(190, 210, 320, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 817, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        Customer c = new Customer();
        LaundryInfo li = new LaundryInfo();
        ServicesAvailed sa = new ServicesAvailed();
        Transaction tr = new Transaction();
        Short s = 1;
        EntityManagerFactory emf =
            Persistence.createEntityManagerFactory("laundry_servicePU");
        EntityManager em = emf.createEntityManager();
        EntityManager en = emf.createEntityManager();
        EntityManager eo = emf.createEntityManager();
        EntityManager fortr = emf.createEntityManager();
        
        
        
        Random rand = new Random();

        int  n = rand.nextInt(100000) + 1;
        int m = rand.nextInt(100000) + 1;
        int l = rand.nextInt(100000) + 1;
        
        Employee elp = new Employee();
        
        
        
        fortr.getTransaction().begin();
        em.getTransaction().begin();
        en.getTransaction().begin();
        eo.getTransaction().begin();
        elp.setEmployeeId(n);
        elp.setName("John Doe");
        elp.setContactNumber(2352);
        elp.setAddress("asfaf");
        elp.setSalary(Float.valueOf(1241));
        elp.setSummary("sadgasdg");
        elp.setPassword("agvbae04t");
        c.setCustomerId(n);
        c.setName(namefield.getText());
        c.setContactNumber(Integer.valueOf(contactfield.getText()));
        c.setAddress(addressfield.getText());
        li.setCustomerId(c);
        li.setClothTypeId(m);
        li.setColoredQuantity((Integer) csq.getValue());
        li.setColoredWeight(Float.valueOf(csw.getValue().toString()));
        li.setWhitesQuantity((Integer) wsq.getValue());
        li.setWhitesWeight(Float.valueOf(wsq.getValue().toString()));
        li.setBedsheetQuantity((Integer) bsq.getValue());
        li.setBedsheetWeight(Float.valueOf(bsw.getValue().toString()));
        li.setBlanketQuantity(Integer.valueOf(blsq.getValue().toString()));
        li.setBlanketWeight(Float.valueOf(blsw.getValue().toString()));
        li.setJeansQuantity(Integer.valueOf(jsw.getValue().toString()));
        li.setJeansWeight(Float.valueOf(jsw.getValue().toString()));
        sa.setLaundryId(li);
        sa.setServiceId(l);
        if(coloredcheck.isSelected())
            sa.setColored(s);
        if(whitescheck.isSelected())
            sa.setColored(s);
        if(heavycheck.isSelected())
            sa.setColored(s);
        if(drycheck.isSelected())
            sa.setColored(s);
        if(ironcheck.isSelected())
            sa.setColored(s);
        if(rushcheck.isSelected())
            sa.setColored(s);
        if(pickupcheck.isSelected())
            sa.setColored(s);
        if(deliverycheck.isSelected())
            sa.setColored(s);
        java.sql.Timestamp timestamp = java.sql.Timestamp.valueOf(java.time.LocalDateTime.now());
        tr.setDateReceived(timestamp);
        tr.setTransactionId(n);
        tr.setEmployeeId(elp);
        tr.setDateClaimed(null);
        tr.setOrNumber(null);
        tr.setServicesId(sa);
        tr.setTotalAmount(Float.valueOf(1000));
        
        em.persist(elp);
        em.persist(c);
        en.persist(li);
        eo.persist(sa);
        fortr.persist(tr);
        
        em.getTransaction().commit();
        en.getTransaction().commit();
        eo.getTransaction().commit();
        fortr.getTransaction().commit();
        fortr.close();
        em.close();
        en.close();
        eo.close();
       
        this.setVisible(false);
        this.dispose();;
        Transactions t = new Transactions();
        t.setVisible(true);
        

    }//GEN-LAST:event_savebuttonActionPerformed

    private void pickupcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickupcheckActionPerformed

    private void rushcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rushcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rushcheckActionPerformed

    private void ironcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ironcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ironcheckActionPerformed

    private void drycheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drycheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drycheckActionPerformed

    private void heavycheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavycheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heavycheckActionPerformed

    private void whitescheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whitescheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whitescheckActionPerformed

    private void deliverycheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverycheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverycheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JSpinner blsq;
    private javax.swing.JSpinner blsw;
    private javax.swing.JSpinner bsq;
    private javax.swing.JSpinner bsw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox coloredcheck;
    private javax.swing.JTextField contactfield;
    private javax.swing.JSpinner csq;
    private javax.swing.JSpinner csw;
    private javax.swing.JCheckBox deliverycheck;
    private javax.swing.JCheckBox drycheck;
    private javax.swing.JCheckBox heavycheck;
    private javax.swing.JCheckBox ironcheck;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jsq;
    private javax.swing.JSpinner jsw;
    private javax.swing.JTextField namefield;
    private javax.swing.JCheckBox pickupcheck;
    private javax.swing.JCheckBox rushcheck;
    private javax.swing.JButton savebutton;
    private javax.swing.JCheckBox whitescheck;
    private javax.swing.JSpinner wsq;
    private javax.swing.JSpinner wsw;
    // End of variables declaration//GEN-END:variables
}
