/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Franklin
 */
public class AdminLaundry extends javax.swing.JFrame {

    /**
     * Creates new form AdminLaundry
     */
    public AdminLaundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_btn = new javax.swing.JButton();
        expense_btn = new javax.swing.JButton();
        transaction_btn = new javax.swing.JButton();
        sales_btn = new javax.swing.JButton();
        quit_btn = new javax.swing.JButton();
        employee_btn = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUBBLE WASH LAUNDRY SERVICES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 660, 80);

        customer_btn.setBackground(new java.awt.Color(0, 153, 153));
        customer_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customer_btn.setForeground(new java.awt.Color(255, 255, 255));
        customer_btn.setText("View Customer");
        customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_btnActionPerformed(evt);
            }
        });
        jPanel1.add(customer_btn);
        customer_btn.setBounds(90, 210, 220, 50);

        expense_btn.setBackground(new java.awt.Color(0, 153, 153));
        expense_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        expense_btn.setForeground(new java.awt.Color(255, 255, 255));
        expense_btn.setText("View Expenses");
        expense_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expense_btnActionPerformed(evt);
            }
        });
        jPanel1.add(expense_btn);
        expense_btn.setBounds(440, 210, 220, 50);

        transaction_btn.setBackground(new java.awt.Color(0, 153, 153));
        transaction_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        transaction_btn.setForeground(new java.awt.Color(255, 255, 255));
        transaction_btn.setText("View Transactions");
        transaction_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_btnActionPerformed(evt);
            }
        });
        jPanel1.add(transaction_btn);
        transaction_btn.setBounds(90, 320, 220, 50);

        sales_btn.setBackground(new java.awt.Color(0, 153, 153));
        sales_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sales_btn.setForeground(new java.awt.Color(255, 255, 255));
        sales_btn.setText("View Daily Sales");
        sales_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sales_btn);
        sales_btn.setBounds(440, 320, 220, 50);

        quit_btn.setBackground(new java.awt.Color(0, 153, 153));
        quit_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        quit_btn.setForeground(new java.awt.Color(255, 255, 255));
        quit_btn.setText("Quit");
        quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(quit_btn);
        quit_btn.setBounds(440, 430, 220, 50);

        employee_btn.setBackground(new java.awt.Color(0, 153, 153));
        employee_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        employee_btn.setForeground(new java.awt.Color(255, 255, 255));
        employee_btn.setText("View Employee");
        employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_btnActionPerformed(evt);
            }
        });
        jPanel1.add(employee_btn);
        employee_btn.setBounds(90, 430, 220, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_btnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_customer_btnActionPerformed

    private void expense_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expense_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Expenses().setVisible(true);
    }//GEN-LAST:event_expense_btnActionPerformed

    private void transaction_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_btnActionPerformed
        // TODO add your handling code here:
        new Transaction().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transaction_btnActionPerformed

    private void sales_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sales().setVisible(true);

    }//GEN-LAST:event_sales_btnActionPerformed

    private void quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btnActionPerformed
        // TODO add your handling code here:
        try {
            System.exit(0);
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_quit_btnActionPerformed

    private void employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_btnActionPerformed
        // TODO add your handling code here:
        try {
            System.exit(0);
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_employee_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton customer_btn;
    private javax.swing.JButton employee_btn;
    private javax.swing.JButton expense_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton quit_btn;
    private javax.swing.JButton sales_btn;
    private javax.swing.JButton transaction_btn;
    // End of variables declaration//GEN-END:variables
}
