/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Franklin
 */
public class EmployeeLaundry extends javax.swing.JFrame {

    /**
     * Creates new form laundry
     */
    public EmployeeLaundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        transaction_btn = new javax.swing.JButton();
        expense_btn = new javax.swing.JButton();
        sales_btn = new javax.swing.JButton();
        quit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        transaction_btn.setBackground(new java.awt.Color(0, 153, 153));
        transaction_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        transaction_btn.setForeground(new java.awt.Color(255, 255, 255));
        transaction_btn.setText("View Transactions");
        transaction_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_btnActionPerformed(evt);
            }
        });
        jPanel1.add(transaction_btn);
        transaction_btn.setBounds(240, 190, 300, 50);

        expense_btn.setBackground(new java.awt.Color(0, 153, 153));
        expense_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        expense_btn.setForeground(new java.awt.Color(255, 255, 255));
        expense_btn.setText("View Expenses");
        jPanel1.add(expense_btn);
        expense_btn.setBounds(240, 290, 300, 50);

        sales_btn.setBackground(new java.awt.Color(0, 153, 153));
        sales_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        sales_btn.setForeground(new java.awt.Color(255, 255, 255));
        sales_btn.setText("View Daily Sales");
        sales_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sales_btn);
        sales_btn.setBounds(240, 390, 300, 50);

        quit_btn.setBackground(new java.awt.Color(0, 153, 153));
        quit_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        quit_btn.setForeground(new java.awt.Color(255, 255, 255));
        quit_btn.setText("Quit");
        quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(quit_btn);
        quit_btn.setBounds(240, 490, 300, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUBBLE WASH LAUNDRY SERVICES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 660, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transaction_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_btnActionPerformed
        // TODO add your handling code here:
        new Transaction().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transaction_btnActionPerformed

    private void quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btnActionPerformed
        // TODO add your handling code here:
        try {
            System.exit(0);
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_quit_btnActionPerformed

    private void sales_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sales().setVisible(true);
        
    }//GEN-LAST:event_sales_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EmployeeLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton expense_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton quit_btn;
    private javax.swing.JButton sales_btn;
    private javax.swing.JButton transaction_btn;
    // End of variables declaration//GEN-END:variables
}
