/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Franklin
 */
public class CustInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustInfo
     */
    public CustInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        colored_spinner = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        colored_spinner2 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSpinner15 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        jSpinner17 = new javax.swing.JSpinner();
        jSpinner18 = new javax.swing.JSpinner();
        jSpinner19 = new javax.swing.JSpinner();
        jSpinner20 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jSpinner21 = new javax.swing.JSpinner();
        jSpinner22 = new javax.swing.JSpinner();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        colored_spinner1 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        colored_spinner3 = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jSpinner23 = new javax.swing.JSpinner();
        jSpinner24 = new javax.swing.JSpinner();
        jSpinner25 = new javax.swing.JSpinner();
        jSpinner26 = new javax.swing.JSpinner();
        jSpinner27 = new javax.swing.JSpinner();
        jSpinner28 = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jSpinner29 = new javax.swing.JSpinner();
        jSpinner30 = new javax.swing.JSpinner();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Transaction");
        setPreferredSize(new java.awt.Dimension(832, 950));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(817, 745));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Services Offered");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 300, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 90, 30);

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameField);
        nameField.setBounds(200, 120, 590, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Contact Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 160, 30);

        contactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactFieldKeyTyped(evt);
            }
        });
        jPanel1.add(contactField);
        contactField.setBounds(200, 170, 590, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 150, 30);

        addressField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressFieldKeyTyped(evt);
            }
        });
        jPanel1.add(addressField);
        addressField.setBounds(200, 222, 590, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Laundry Information");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 220, 30);
        jPanel1.add(colored_spinner);
        colored_spinner.setBounds(340, 390, 60, 30);
        jPanel1.add(jSpinner3);
        jSpinner3.setBounds(340, 690, 60, 30);
        jPanel1.add(jSpinner4);
        jSpinner4.setBounds(200, 490, 60, 30);
        jPanel1.add(jSpinner5);
        jSpinner5.setBounds(200, 540, 60, 30);
        jPanel1.add(jSpinner6);
        jSpinner6.setBounds(200, 590, 60, 30);
        jPanel1.add(jSpinner7);
        jSpinner7.setBounds(200, 640, 60, 30);
        jPanel1.add(jSpinner8);
        jSpinner8.setBounds(340, 740, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Colored");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 390, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Heavy");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 490, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Dry Clean");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 540, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Iron");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 590, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Rush");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 640, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Delivery");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 740, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Weight");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 340, 90, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Quantity");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(190, 340, 90, 30);
        jPanel1.add(colored_spinner2);
        colored_spinner2.setBounds(200, 390, 60, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(440, 290, 20, 510);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Whites");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(20, 440, 100, 30);
        jPanel1.add(jSpinner15);
        jSpinner15.setBounds(200, 440, 60, 30);
        jPanel1.add(jSpinner16);
        jSpinner16.setBounds(340, 440, 60, 30);
        jPanel1.add(jSpinner17);
        jSpinner17.setBounds(340, 490, 60, 30);
        jPanel1.add(jSpinner18);
        jSpinner18.setBounds(340, 540, 60, 30);
        jPanel1.add(jSpinner19);
        jSpinner19.setBounds(340, 590, 60, 30);
        jPanel1.add(jSpinner20);
        jSpinner20.setBounds(340, 640, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Basic Information");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 70, 190, 40);

        jCheckBox1.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox1.setText("Delivery");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(500, 760, 160, 30);

        jCheckBox2.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox2.setText("Colored");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(500, 350, 160, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("Pick-up");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(20, 690, 100, 30);
        jPanel1.add(jSpinner21);
        jSpinner21.setBounds(200, 690, 60, 30);
        jPanel1.add(jSpinner22);
        jSpinner22.setBounds(200, 740, 60, 30);

        jCheckBox3.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox3.setText("Whites");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(500, 410, 160, 30);

        jCheckBox4.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox4.setText("Heavy");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(500, 470, 160, 30);

        jCheckBox5.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox5.setText("Dry Clean");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(500, 530, 160, 30);

        jCheckBox6.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox6.setText("Iron");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(500, 590, 160, 30);

        jCheckBox7.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox7.setText("Rush");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(500, 650, 160, 30);

        jCheckBox8.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox8.setText("Pick-up");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(500, 710, 160, 30);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(20, 290, 760, 2);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(30, 800, 760, 10);

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(817, 745));
        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Services Offered");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(490, 300, 190, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Name");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 120, 90, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(200, 120, 590, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Contact Number");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 170, 160, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(200, 170, 590, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Address");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 220, 150, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(200, 222, 590, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Laundry Information");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 300, 220, 30);
        jPanel2.add(colored_spinner1);
        colored_spinner1.setBounds(340, 390, 60, 30);
        jPanel2.add(jSpinner9);
        jSpinner9.setBounds(340, 690, 60, 30);
        jPanel2.add(jSpinner10);
        jSpinner10.setBounds(200, 490, 60, 30);
        jPanel2.add(jSpinner11);
        jSpinner11.setBounds(200, 540, 60, 30);
        jPanel2.add(jSpinner12);
        jSpinner12.setBounds(200, 590, 60, 30);
        jPanel2.add(jSpinner13);
        jSpinner13.setBounds(200, 640, 60, 30);
        jPanel2.add(jSpinner14);
        jSpinner14.setBounds(340, 740, 60, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("Colored");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 390, 100, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Heavy");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 490, 100, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Dry Clean");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 540, 100, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("Iron");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(20, 590, 100, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Rush");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(20, 640, 100, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Delivery");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(20, 740, 100, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Weight");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(340, 340, 90, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("Quantity");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(190, 340, 90, 30);
        jPanel2.add(colored_spinner3);
        colored_spinner3.setBounds(200, 390, 60, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(440, 290, 20, 510);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 240, 240));
        jLabel32.setText("Whites");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(20, 440, 100, 30);
        jPanel2.add(jSpinner23);
        jSpinner23.setBounds(200, 440, 60, 30);
        jPanel2.add(jSpinner24);
        jSpinner24.setBounds(340, 440, 60, 30);
        jPanel2.add(jSpinner25);
        jSpinner25.setBounds(340, 490, 60, 30);
        jPanel2.add(jSpinner26);
        jSpinner26.setBounds(340, 540, 60, 30);
        jPanel2.add(jSpinner27);
        jSpinner27.setBounds(340, 590, 60, 30);
        jPanel2.add(jSpinner28);
        jSpinner28.setBounds(340, 640, 60, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Basic Information");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(20, 70, 190, 40);

        jCheckBox9.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox9.setText("Delivery");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox9);
        jCheckBox9.setBounds(500, 760, 160, 30);

        jCheckBox10.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox10.setText("Colored");
        jPanel2.add(jCheckBox10);
        jCheckBox10.setBounds(500, 350, 160, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(240, 240, 240));
        jLabel34.setText("Pick-up");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(20, 690, 100, 30);
        jPanel2.add(jSpinner29);
        jSpinner29.setBounds(200, 690, 60, 30);
        jPanel2.add(jSpinner30);
        jSpinner30.setBounds(200, 740, 60, 30);

        jCheckBox11.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox11.setText("Whites");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox11);
        jCheckBox11.setBounds(500, 410, 160, 30);

        jCheckBox12.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox12.setText("Heavy");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox12);
        jCheckBox12.setBounds(500, 470, 160, 30);

        jCheckBox13.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox13.setText("Dry Clean");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox13);
        jCheckBox13.setBounds(500, 530, 160, 30);

        jCheckBox14.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox14.setText("Iron");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox14);
        jCheckBox14.setBounds(500, 590, 160, 30);

        jCheckBox15.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox15.setText("Rush");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox15);
        jCheckBox15.setBounds(500, 650, 160, 30);

        jCheckBox16.setBackground(new java.awt.Color(51, 51, 0));
        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBox16.setText("Pick-up");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox16);
        jCheckBox16.setBounds(500, 710, 160, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(20, 290, 760, 2);
        jPanel2.add(jSeparator8);
        jSeparator8.setBounds(20, 290, 760, 90);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("NEW TRANSACTION");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(160, 16, 470, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 817, 800);

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 830, 300, 50);

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("SAVE");
        jPanel1.add(jButton2);
        jButton2.setBounds(490, 830, 300, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transaction().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        // TODO add your handling code here:
        if(nameField.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void contactFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') ||
             (c == java.awt.event.KeyEvent.VK_BACK_SPACE) ||
             (c == java.awt.event.KeyEvent.VK_DELETE))) {
              // getToolkit().beep();
              evt.consume();
        }

        if(contactField.getText().length()>9) {
              evt.consume();
        }
    }//GEN-LAST:event_contactFieldKeyTyped

    private void addressFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressFieldKeyTyped
        // TODO add your handling code here:
        if(addressField.getText().length() > 50) {
            evt.consume();
        }
    }//GEN-LAST:event_addressFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JSpinner colored_spinner;
    private javax.swing.JSpinner colored_spinner1;
    private javax.swing.JSpinner colored_spinner2;
    private javax.swing.JSpinner colored_spinner3;
    private javax.swing.JTextField contactField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner19;
    private javax.swing.JSpinner jSpinner20;
    private javax.swing.JSpinner jSpinner21;
    private javax.swing.JSpinner jSpinner22;
    private javax.swing.JSpinner jSpinner23;
    private javax.swing.JSpinner jSpinner24;
    private javax.swing.JSpinner jSpinner25;
    private javax.swing.JSpinner jSpinner26;
    private javax.swing.JSpinner jSpinner27;
    private javax.swing.JSpinner jSpinner28;
    private javax.swing.JSpinner jSpinner29;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner30;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
